### PR TITLE
Moved instructions to the docs

### PR DESCRIPTION
**Pull request by criadoperez**
## Description

Instructions on how to use this script has been moved to the docs so it needs to be removed from here, to simplify future updates, avoid duplication, and enable instructions in multiple languages.

They are now available here instead: https://docs.stacks.co/docs/nodes-and-miners/run-a-node

### CODE REVIEW

**Comment by wileyj** [comment]
No. It may be on the docs website, but the docs website should not be the source of truth for a repo's documentation. 
Consider an update that changes how the script works - typically that would mean updating the files in a repo - with this change, it would require updating the files in this repo, then also updating the files in a separate repo to explain how to use the changes.

**Comment by criadoperez** [comment]
> with this change, it would require updating the files in this repo, then also updating the files in a separate repo to explain how to use the changes.

No. This is what is happening now without the change and I wanted to stop...
If we make a change in the script that requires a change in the documentation, we will now have to make changes on two separate places (the readme.md file in the repo and the docs site). With time both manuals diverge...

With the update I'm suggestion we would only update the docs.

> the docs website should not be the source of truth for a repo's documentation

Yes, this is what I was suggesting. :-) 

If however you don't like this for this repo, would you consider some middle ground? Maybe only leaving some sort of basic docs on the README.md file?

If not, if we do leave everything duplicated, I would at least leave a footnote or something on the README.md file, as a reminder that any changes should also be replicated into the docs.

**Comment by wileyj** [comment]
> If however you don't like this for this repo, would you consider some middle ground? Maybe only leaving some sort of basic docs on the README.md file?
> 
> If not, if we do leave everything duplicated, I would at least leave a footnote or something on the README.md file, as a reminder that any changes should also be replicated into the docs.

Removing the docs from a standalone repo is not a tenable idea - an open source repo should be able to stand by itself without relying on external sources. 
The only middle ground I can envision here is either/and:
1. move most of the readme contents to a `./docs` subfolder, and link to the website
2. create a github action to PR doc changes to the website

**Comment by criadoperez** [comment]
We could look into that option. In that scenario the docs can get edited from both sites (docs and github repo), so this github action would have to deal with changes from both sides. It's possible, but can get messy. 

Anyway, this solution would require some development, so for now I guess we will just have to deal with the duplication of the docs on both sites and leave it as it is.

**Pull request closed without merging**
